# Translations template for cinder.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the cinder project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2014.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: cinder 2015.1.dev352.g0b74d6b\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-12-05 06:07+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: cinder/api/openstack/__init__.py:114
#, python-format
msgid ""
"Extension %(ext_name)s: Cannot extend resource %(collection)s: No such "
"resource"
msgstr ""

#: cinder/backup/api.py:142
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create %(s_size)sG backup "
"(%(d_consumed)dG of %(d_quota)dG already consumed)"
msgstr ""

#: cinder/backup/api.py:154
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create backups (%(d_consumed)d "
"backups already consumed)"
msgstr ""

#: cinder/backup/manager.py:592
#, python-format
msgid ""
"Backup service %(service)s does not support verify. Backup id %(id)s is "
"not verified. Skipping verify."
msgstr ""

#: cinder/backup/drivers/ceph.py:1188
#, python-format
msgid ""
"RBD image for backup %(backup)s of volume %(volume)s not found. Deleting "
"backup metadata."
msgstr ""

#: cinder/backup/drivers/swift.py:517
msgid "swift error while listing objects, continuing with delete"
msgstr ""

#: cinder/backup/drivers/swift.py:526
#, python-format
msgid "swift error while deleting object %s, continuing with delete"
msgstr ""

#: cinder/brick/iscsi/iscsi.py:153 cinder/volume/targets/tgt.py:93
msgid "Attempting recreate of backing lun..."
msgstr ""

#: cinder/brick/iscsi/iscsi.py:254 cinder/volume/targets/tgt.py:235
#, python-format
msgid "Failed to create iscsi target for volume id:%(vol_id)s: %(e)s"
msgstr ""

#: cinder/brick/iscsi/iscsi.py:258
msgid "Create iscsi target failed for target already exists"
msgstr ""

#: cinder/brick/iscsi/iscsi.py:309 cinder/volume/targets/tgt.py:336
#, python-format
msgid "Volume path %s does not exist, nothing to remove."
msgstr ""

#: cinder/brick/iscsi/iscsi.py:345 cinder/volume/targets/tgt.py:370
msgid "Silent failure of target removal detected, retry...."
msgstr ""

#: cinder/brick/local_dev/lvm.py:273
#, python-format
msgid "Took %s seconds to get logical volume info."
msgstr ""

#: cinder/brick/local_dev/lvm.py:371
#, python-format
msgid "Took %s seconds to get volume groups."
msgstr ""

#: cinder/db/sqlalchemy/api.py:893
#, python-format
msgid "Change will make usage less than 0 for the following resources: %s"
msgstr ""

#: cinder/image/glance.py:133
msgid ""
"glance_num_retries shouldn't be a negative value. The number of retries "
"will be set to 0 until this iscorrected in the cinder.conf."
msgstr ""

#: cinder/openstack/common/loopingcall.py:87
#, python-format
msgid "task %(func_name)s run outlasted interval by %(delay).2f sec"
msgstr ""

#: cinder/openstack/common/policy.py:258
#, python-format
msgid "Can not find policy directory: %s"
msgstr ""

#: cinder/openstack/common/service.py:356
#, python-format
msgid "pid %d not in child list"
msgstr ""

#: cinder/scheduler/filter_scheduler.py:400
#, python-format
msgid "No weighed hosts found for volume with properties: %s"
msgstr ""

#: cinder/scheduler/filters/capacity_filter.py:62
#, python-format
msgid ""
"Insufficient free space for volume creation on host %(host)s (requested /"
" avail): %(requested)s/%(available)s"
msgstr ""

#: cinder/tests/test_netapp_nfs.py:359
#, python-format
msgid "Share %(share)s and file name %(file_name)s"
msgstr ""

#: cinder/volume/manager.py:821
#, python-format
msgid "Deleting image %(image_id)s in %(image_status)s state."
msgstr ""

#: cinder/volume/manager.py:827
#, python-format
msgid "Error occurred while deleting image %s."
msgstr ""

#: cinder/volume/manager.py:1224
#, python-format
msgid ""
"Unable to update stats, %(driver_name)s -%(driver_version)s "
"%(config_group)s driver is uninitialized."
msgstr ""

#: cinder/volume/manager.py:1613
#, python-format
msgid ""
"Unable to update volume replication status, %(driver_name)s "
"-%(driver_version)s %(config_group)s driver is uninitialized."
msgstr ""

#: cinder/volume/drivers/eqlx.py:381
#, python-format
msgid "Volume %s was not found while trying to delete it."
msgstr ""

#: cinder/volume/drivers/eqlx.py:496
#, python-format
msgid "Volume %s is not found!, it may have been deleted."
msgstr ""

#: cinder/volume/drivers/fujitsu_eternus_dx_common.py:792
#, python-format
msgid ""
"Snapshot: %(snapshot)s: volume: %(volume)s. Snapshot deleted but cleanup "
"timed out."
msgstr ""

#: cinder/volume/drivers/fujitsu_eternus_dx_common.py:805
#, python-format
msgid ""
"Snapshot: %(snapshot)s: volume: %(volume)s. Snapshot deleted but error "
"during cleanup. Error: %(error)s"
msgstr ""

#: cinder/volume/drivers/glusterfs.py:190
#, python-format
msgid "Failed to refresh mounts, reason=%s"
msgstr ""

#: cinder/volume/drivers/glusterfs.py:279 cinder/volume/drivers/remotefs.py:213
#, python-format
msgid "Volume %s does not have provider_location specified, skipping"
msgstr ""

#: cinder/volume/drivers/lvm.py:247
#, python-format
msgid "snapshot: %s not found, skipping delete operations"
msgstr ""

#: cinder/volume/drivers/lvm.py:349
#, python-format
msgid "Unable to update stats on non-initialized Volume Group: %s"
msgstr ""

#: cinder/volume/drivers/lvm.py:527
#, python-format
msgid "Error creating iSCSI target, retrying creation for target: %s"
msgstr ""

#: cinder/volume/drivers/pure.py:148
#, python-format
msgid "Volume deletion failed with message: %s"
msgstr ""

#: cinder/volume/drivers/pure.py:199
#, python-format
msgid ""
"iSCSI discovery of port %(port_name)s at %(port_portal)s failed with "
"error: %(err_msg)s"
msgstr ""

#: cinder/volume/drivers/rbd.py:177
msgid "flush() not supported in this version of librbd"
msgstr ""

#: cinder/volume/drivers/remotefs.py:291
#, python-format
msgid "%(path)s is being set with open permissions: %(perm)s"
msgstr ""

#: cinder/volume/drivers/remotefs.py:441
#, python-format
msgid "%s is already mounted"
msgstr ""

#: cinder/volume/drivers/remotefs.py:474
#, python-format
msgid ""
"The NAS file operations will be run as root: allowing root level access "
"at the storage backend. This is considered an insecure NAS environment. "
"Please see %s for information on a secure NAS configuration."
msgstr ""

#: cinder/volume/drivers/remotefs.py:481
#, python-format
msgid ""
"The NAS file permissions mode will be 666 (allowing other/world read & "
"write access). This is considered an insecure NAS environment. Please see"
" %s for information on a secure NFS configuration."
msgstr ""

#: cinder/volume/drivers/solidfire.py:408
#, python-format
msgid "More than one valid preset was detected, using %s"
msgstr ""

#: cinder/volume/drivers/xio.py:471
#, python-format
msgid "IOnetworks GET failed (%d)"
msgstr ""

#: cinder/volume/drivers/xio.py:601
#, python-format
msgid "Could not get status for %(name)s (%(status)d)."
msgstr ""

#: cinder/volume/drivers/xio.py:609
msgid "No volume node in XML content."
msgstr ""

#: cinder/volume/drivers/xio.py:617
#, python-format
msgid "No status payload for volume %s."
msgstr ""

#: cinder/volume/drivers/xio.py:707
#, python-format
msgid "Volume %(name)s already presented (%(status)d)!"
msgstr ""

#: cinder/volume/drivers/xio.py:984
#, python-format
msgid "Could not get pool information (%s)!"
msgstr ""

#: cinder/volume/drivers/xio.py:1224
#, python-format
msgid "Delete volume: %s not found!"
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:717
msgid ""
"The VMAX plugin only supports Retype.  If a pool based migration is "
"necessary this will happen on a Retype From the command line: cinder "
"--os-volume-api-version 2 retype <volumeId> <volumeType> --migration-"
"policy on-demand"
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:751
#, python-format
msgid ""
"Failed to migrate: %(volumeName)s from default source storage group for "
"FAST policy: %(sourceFastPolicyName)s Attempting cleanup... "
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:777
#, python-format
msgid ""
"Attempting a rollback of: %(volumeName)s to original pool "
"%(sourcePoolInstanceName)s "
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:808
#, python-format
msgid "_migrate_rollback on : %(volumeName)s from "
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:846
#, python-format
msgid "_migrate_cleanup on : %(volumeName)s from "
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_common.py:2086
#, python-format
msgid ""
"Pre check for deletion Volume: %(volumeName)s is part of a storage group "
"Attempting removal from %(storageGroupInstanceName)s "
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_fast.py:404
msgid "Unable to get storage tiers from tier policy rule  "
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:185
#: cinder/volume/drivers/emc/emc_vmax_masking.py:693
#, python-format
msgid "Volume: %(volumeName)s is already part of storage group %(sgGroupName)s "
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:256
#, python-format
msgid ""
"The volume is already part of storage group: "
"%(storageGroupInstanceName)s. "
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:816
#, python-format
msgid "No storage group found. %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:1413
#, python-format
msgid "No target ports found in masking view %(maskingView)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vmax_masking.py:1459
#, python-format
msgid "No port group found in masking view %(mv)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:334
#, python-format
msgid "LUN already exists, LUN name %(name)s. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:362
#, python-format
msgid "LUN is already deleted, LUN name %(name)s. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:409
#, python-format
msgid "LUN %(name)s is already expanded. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:466
#, python-format
msgid "Consistency group %(name)s already exists. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:535
#, python-format
msgid "CG %(cg_name)s does not exist. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:539
#, python-format
msgid "CG %(cg_name)s is deleting. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:565
#, python-format
msgid "Cgsnapshot name %(name)s already exists. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:583
#, python-format
msgid "Snapshot %(name)s for consistency group does not exist. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:604
#, python-format
msgid "Snapshot %(name)s already exists. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:624
#, python-format
msgid "Snapshot %(name)s may deleted already. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:631
#, python-format
msgid "Snapshot %(name)s is in use, retry. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:658
#, python-format
msgid "Mount point %(name)s already exists. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:677
#, python-format
msgid ""
"Snapshot %(snapname)s is attached to snapshot mount point %(mpname)s "
"already. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:731
#, python-format
msgid ""
"Migration command may get network timeout. Double check whether migration"
" in fact started successfully. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:742
#, python-format
msgid "Start migration failed. Message: %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:825
#, python-format
msgid "Storage group %(name)s already exists. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:842
#, python-format
msgid ""
"Storage group %(name)s doesn't exist, may have already been deleted. "
"Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:874
#, python-format
msgid ""
"Host %(host)s has already disconnected from storage group %(sgname)s. "
"Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:894
#, python-format
msgid ""
"LUN %(lun)s has already added to Storage Group %(sgname)s. Message: "
"%(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:914
#, python-format
msgid "HLU %(hlu)s has already been removed from %(sgname)s. Message: %(msg)s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1069
msgid "No array serial number returned, set as unknown."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1248
#, python-format
msgid "See unavailable iSCSI target: %s"
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1454
msgid ""
"destroy_empty_storage_group: True. Empty storage group will be deleted "
"after volume is detached."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1617
msgid ""
"Failed to get target_pool_name and target_array_serial. 'location_info' "
"is not in host['capabilities']."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1630
msgid "Error on parsing target_pool_name/target_array_serial."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:1748
msgid "Storage-assisted migration failed during retype."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2105
#, python-format
msgid "Storage Group %s is not found. Create it."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2435
#, python-format
msgid "Storage Group %s is not found. terminate_connection() is unnecessary."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2443
#, python-format
msgid "Volume %s is not found. It has probably been removed in VNX."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2451
#, python-format
msgid "Volume %(vol)s was not in Storage Group %(sg)s."
msgstr ""

#: cinder/volume/drivers/emc/emc_vnx_cli.py:2469
#, python-format
msgid "Failed to destroy Storage Group %s."
msgstr ""

#: cinder/volume/drivers/emc/xtremio.py:88
#, python-format
msgid "object %(key)s of type %(typ)s not found"
msgstr ""

#: cinder/volume/drivers/emc/xtremio.py:242
msgid "terminate_connection: lun map not found"
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem.py:370
#, python-format
msgid "warning: Tried to delete vdisk %s but it does not exist."
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem.py:407
#, python-format
msgid "_execute_command_and_parse_attributes: Failed to run command: %s."
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem.py:608
#, python-format
msgid "_get_vdisk_map_properties: Did not find a preferred node for vdisk %s."
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem.py:850
msgid "_remove_device: invalid properties or device."
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem.py:903
#, python-format
msgid ""
"_unmap_vdisk_from_host: No mapping of volume %(vol_name)s to any host "
"found."
msgstr ""

#: cinder/volume/drivers/ibm/flashsystem.py:909
#, python-format
msgid ""
"_unmap_vdisk_from_host: Multiple mappings of volume %(vdisk_name)s found,"
" no host specified."
msgstr ""

#: cinder/volume/drivers/ibm/ibmnas.py:287
#, python-format
msgid "Volume %s does not have provider_location specified, skipping."
msgstr ""

#: cinder/volume/drivers/netapp/utils.py:59
msgid ""
"It is not the recommended way to use drivers by NetApp. Please use "
"NetAppDriver to achieve the functionality."
msgstr ""

#: cinder/volume/drivers/netapp/utils.py:131
#, python-format
msgid "Extra spec %(old)s is obsolete.  Use %(new)s instead."
msgstr ""

#: cinder/volume/drivers/netapp/utils.py:136
#, python-format
msgid "Extra spec %(old)s is deprecated.  Use %(new)s instead."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/block_7mode.py:106
#, python-format
msgid "Could not determine root volume name on %s."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/block_7mode.py:268
msgid "Volume refresh job already running. Returning..."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/block_7mode.py:275
#, python-format
msgid "Error refreshing volume info. Message: %s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/block_base.py:161
#, python-format
msgid "No entry in LUN table for volume/snapshot %(name)s."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:240
#, python-format
msgid ""
"Exception while registering image %(image_id)s in cache. Exception: "
"%(exc)s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:308
#, python-format
msgid "Exception during cache cleaning %(share)s. Message - %(ex)s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:366
#, python-format
msgid "Exception during deleting %s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:427
#, python-format
msgid "Unexpected exception during image cloning in share %s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:518
msgid "Discover file retries exhausted."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:576
msgid "Unexpected exception while short listing used share."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:639
#, python-format
msgid "Destination %s already exists."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_base.py:647
#, python-format
msgid "Exception moving file %(src)s. Message - %(e)s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_cmode.py:110
#, python-format
msgid "Exception creating vol %(name)s on share %(share)s. Details: %(ex)s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/nfs_cmode.py:244
msgid "No shares found hence skipping ssc refresh."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/ssc_cmode.py:506
msgid "ssc job in progress. Returning... "
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/ssc_cmode.py:518
msgid "refresh stale ssc job in progress. Returning... "
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/ssc_cmode.py:621
#, python-format
msgid ""
"The user does not have access or sufficient privileges to use all netapp "
"APIs. The following extra_specs will fail or be ignored: %s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/client/client_7mode.py:84
#, python-format
msgid "Error finding LUNs for volume %s. Verify volume exists."
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/client/client_base.py:112
#, python-format
msgid "Error mapping LUN. Code :%(code)s, Message:%(message)s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/client/client_base.py:125
#, python-format
msgid "Error unmapping LUN. Code :%(code)s, Message:%(message)s"
msgstr ""

#: cinder/volume/drivers/netapp/dataontap/client/client_base.py:313
#, python-format
msgid "Failed to invoke ems. Message : %s"
msgstr ""

#: cinder/volume/drivers/netapp/eseries/iscsi.py:132
#, python-format
msgid ""
"Production use of \"%(backend)s\" backend requires the Cinder controller "
"to have multipathing properly set up and the configuration option "
"\"%(mpflag)s\" to be set to \"True\"."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/iscsi.py:431
msgid "Snapshot volume not found."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/iscsi.py:472
#, python-format
msgid "Failure deleting job %s."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/iscsi.py:475
#, python-format
msgid "Volume copy job for src vol %s not found."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/iscsi.py:489
#, python-format
msgid "Failure deleting temp snapshot %s."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/iscsi.py:533
#, python-format
msgid "Snapshot %s already deleted."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/iscsi.py:650
#, python-format
msgid "Unable to update host type for host with label %(l)s. %(e)s"
msgstr ""

#: cinder/volume/drivers/netapp/eseries/iscsi.py:655
#, python-format
msgid "Message - %s."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/iscsi.py:776
#, python-format
msgid "No storage pool found with available capacity %s."
msgstr ""

#: cinder/volume/drivers/netapp/eseries/iscsi.py:809
msgid "Returning as clean tmp vol job already running."
msgstr ""

#: cinder/volume/drivers/nexenta/iscsi.py:181
#, python-format
msgid "Cannot delete snapshot %(origin)s: %(exc)s"
msgstr ""

#: cinder/volume/drivers/nexenta/iscsi.py:207
#: cinder/volume/drivers/nexenta/nfs.py:208
#, python-format
msgid "Failed to delete zfs snapshot %(volume_name)s@%(name)s"
msgstr ""

#: cinder/volume/drivers/nexenta/iscsi.py:269
#, python-format
msgid "Remote NexentaStor appliance at %s should be SSH-bound."
msgstr ""

#: cinder/volume/drivers/nexenta/iscsi.py:289
#, python-format
msgid ""
"Cannot send source snapshot %(src)s to destination %(dst)s. Reason: "
"%(exc)s"
msgstr ""

#: cinder/volume/drivers/nexenta/iscsi.py:297
#, python-format
msgid ""
"Cannot delete temporary source snapshot %(src)s on NexentaStor Appliance:"
" %(exc)s"
msgstr ""

#: cinder/volume/drivers/nexenta/iscsi.py:303
#, python-format
msgid "Cannot delete source volume %(volume)s on NexentaStor Appliance: %(exc)s"
msgstr ""

#: cinder/volume/drivers/nexenta/iscsi.py:313
#, python-format
msgid ""
"Cannot delete temporary destination snapshot %(dst)s on NexentaStor "
"Appliance: %(exc)s"
msgstr ""

#: cinder/volume/drivers/nexenta/iscsi.py:552
#, python-format
msgid ""
"Got error trying to destroy target group %(target_group)s, assuming it is"
" already gone: %(exc)s"
msgstr ""

#: cinder/volume/drivers/nexenta/iscsi.py:560
#, python-format
msgid ""
"Got error trying to delete target %(target)s, assuming it is already "
"gone: %(exc)s"
msgstr ""

#: cinder/volume/drivers/nexenta/nfs.py:149
#, python-format
msgid "Cannot destroy created folder: %(vol)s/%(folder)s"
msgstr ""

#: cinder/volume/drivers/nexenta/nfs.py:179
#, python-format
msgid "Cannot destroy cloned folder: %(vol)s/%(folder)s"
msgstr ""

#: cinder/volume/drivers/prophetstor/dpl_iscsi.py:154
#, python-format
msgid "Cannot get volume status %(exc)%s."
msgstr ""

#: cinder/volume/drivers/prophetstor/dplcommon.py:1183
#, python-format
msgid "Flexvisor failed to delete volume %(id)s from the group %(vgid)s."
msgstr ""

#: cinder/volume/drivers/prophetstor/dplcommon.py:1188
#, python-format
msgid ""
"Flexvisor failed to delete volume %(id)s from group %(vgid)s due to "
"%(status)s."
msgstr ""

#: cinder/volume/drivers/prophetstor/dplcommon.py:1364
#, python-format
msgid "Failed to query pool %(id)s status %(ret)d."
msgstr ""

#: cinder/volume/drivers/san/hp/hp_3par_fc.py:325
#, python-format
msgid "Found HOSTS %s"
msgstr ""

#: cinder/volume/drivers/vmware/datastore.py:218
#, python-format
msgid "Unable to fetch datastores connected to host %s."
msgstr ""

#: cinder/volume/targets/iscsi.py:131
msgid "ISCSI provider_location not stored, using discovery"
msgstr ""

